### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by ichayer** [ThomasMiz/socks5-server#18]
- [x] Add CMD_CHANGE_PASSWORD to management protocol.
- [x] Add CMD_CHANGE_ROLE to management protocol.
- [x] Add CMD_GET_AUTHENTICATION_STATUS to management protocol.
- [x] Add CMD_SET_AUTHENTICATION_STATUS to management protocol.
- [x] Add CMD_USERS to management protocol.
- [x] Check that the protocol is the same as in the docs.
- [x] Check send file in copy.c
- [x] Document all functions
- [x] Remove spanish and unnecessary comments
- [x] Check that only registered clients and administrators can access socks5 protocol and that administrators can only access the monitoring protocol.
- [x] Check iconsistency in response messages (capital letter after OK or ERR)
- [x] cmdSetAuthenticationStatus and cmdSetDissectorStatus have the same code, try to merge them into only one.
- [x] Solve compilation warnings
- [x] Project must compile in Pampero
- [x] Generate new JMeter graphs
- [x] Make always rebuilds everything, fix it.
- [x] Check statistics.
- [x] Push report
- [x] Client always looks for 8080 port.
- [x]  cpp-check, PVS-Studio.

**Comment by ichayer** [comment]
Kevin and Ill take the first five bullets.

**Comment by camilaDiToro** [comment]
Esto es del lado del cliente o del servidor? 
 _cmdSetAuthenticationStatus and cmdSetDissectorStatus have the same code, try to merge them into only one._
Del lado del servidor se puede hacer un define, pero no me parece mal como está ahora

No voy a mirar este porque no hice nada de eso y voy a pififiar seguro
_Check that only registered clients and administrators can access socks5 protocol and that administrators can only access the monitoring protocol._

**Comment by ichayer** [comment]
> Esto es del lado del cliente o del servidor?
> _cmdSetAuthenticationStatus and cmdSetDissectorStatus have the same code, try to merge them into only one._
> Del lado del servidor se puede hacer un define, pero no me parece mal como está ahora

Client side.
